// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode_wrapper.proto

package message // import "github.com/commis/fabric-client-go/grpc/message"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChaincodeRequest_Method int32

const (
	ChaincodeRequest_QUERY  ChaincodeRequest_Method = 0
	ChaincodeRequest_INVOKE ChaincodeRequest_Method = 1
)

var ChaincodeRequest_Method_name = map[int32]string{
	0: "QUERY",
	1: "INVOKE",
}
var ChaincodeRequest_Method_value = map[string]int32{
	"QUERY":  0,
	"INVOKE": 1,
}

func (x ChaincodeRequest_Method) String() string {
	return proto.EnumName(ChaincodeRequest_Method_name, int32(x))
}
func (ChaincodeRequest_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chaincode_wrapper_19412e8740f58aa7, []int{0, 0}
}

type ChaincodeRequest struct {
	Chaincode            string                  `protobuf:"bytes,1,opt,name=chaincode,proto3" json:"chaincode,omitempty"`
	Method               ChaincodeRequest_Method `protobuf:"varint,2,opt,name=method,proto3,enum=message.ChaincodeRequest_Method" json:"method,omitempty"`
	Operator             string                  `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Args                 string                  `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ChaincodeRequest) Reset()         { *m = ChaincodeRequest{} }
func (m *ChaincodeRequest) String() string { return proto.CompactTextString(m) }
func (*ChaincodeRequest) ProtoMessage()    {}
func (*ChaincodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaincode_wrapper_19412e8740f58aa7, []int{0}
}
func (m *ChaincodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeRequest.Unmarshal(m, b)
}
func (m *ChaincodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeRequest.Marshal(b, m, deterministic)
}
func (dst *ChaincodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeRequest.Merge(dst, src)
}
func (m *ChaincodeRequest) XXX_Size() int {
	return xxx_messageInfo_ChaincodeRequest.Size(m)
}
func (m *ChaincodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeRequest proto.InternalMessageInfo

func (m *ChaincodeRequest) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *ChaincodeRequest) GetMethod() ChaincodeRequest_Method {
	if m != nil {
		return m.Method
	}
	return ChaincodeRequest_QUERY
}

func (m *ChaincodeRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ChaincodeRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ResultResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaincode_wrapper_19412e8740f58aa7, []int{1}
}
func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (dst *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(dst, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResultResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ResultResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChaincodeRequest)(nil), "message.ChaincodeRequest")
	proto.RegisterType((*ResultResponse)(nil), "message.ResultResponse")
	proto.RegisterEnum("message.ChaincodeRequest_Method", ChaincodeRequest_Method_name, ChaincodeRequest_Method_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeServiceClient is the client API for ChaincodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeServiceClient interface {
	Send(ctx context.Context, in *ChaincodeRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type chaincodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeServiceClient(cc *grpc.ClientConn) ChaincodeServiceClient {
	return &chaincodeServiceClient{cc}
}

func (c *chaincodeServiceClient) Send(ctx context.Context, in *ChaincodeRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/message.ChaincodeService/send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaincodeServiceServer is the server API for ChaincodeService service.
type ChaincodeServiceServer interface {
	Send(context.Context, *ChaincodeRequest) (*ResultResponse, error)
}

func RegisterChaincodeServiceServer(s *grpc.Server, srv ChaincodeServiceServer) {
	s.RegisterService(&_ChaincodeService_serviceDesc, srv)
}

func _ChaincodeService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.ChaincodeService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServiceServer).Send(ctx, req.(*ChaincodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChaincodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.ChaincodeService",
	HandlerType: (*ChaincodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "send",
			Handler:    _ChaincodeService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaincode_wrapper.proto",
}

func init() {
	proto.RegisterFile("chaincode_wrapper.proto", fileDescriptor_chaincode_wrapper_19412e8740f58aa7)
}

var fileDescriptor_chaincode_wrapper_19412e8740f58aa7 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x9b, 0xf7, 0x6d, 0xa3, 0x19, 0xa4, 0x94, 0x05, 0x69, 0x2c, 0x82, 0x25, 0xa7, 0x5e,
	0x9a, 0x40, 0xf5, 0xe0, 0xc1, 0x53, 0xa5, 0x07, 0x11, 0xb5, 0xae, 0xa8, 0x28, 0x48, 0xd9, 0x6e,
	0xc6, 0x4d, 0xa4, 0xcd, 0xae, 0xbb, 0xdb, 0x8a, 0x9f, 0xcd, 0x2f, 0x27, 0xdd, 0xa6, 0xf1, 0x0f,
	0x78, 0x9b, 0x9d, 0x79, 0xe6, 0xc7, 0xb3, 0xf3, 0x40, 0x9b, 0x67, 0x2c, 0x2f, 0xb8, 0x4c, 0x71,
	0xf2, 0xa6, 0x99, 0x52, 0xa8, 0x63, 0xa5, 0xa5, 0x95, 0x64, 0x6b, 0x8e, 0xc6, 0x30, 0x81, 0xd1,
	0x87, 0x07, 0xad, 0xd3, 0x8d, 0x88, 0xe2, 0xeb, 0x02, 0x8d, 0x25, 0xfb, 0x10, 0x54, 0x8b, 0xa1,
	0xd7, 0xf5, 0x7a, 0x01, 0xfd, 0x6a, 0x90, 0x63, 0xf0, 0xe7, 0x68, 0x33, 0x99, 0x86, 0xff, 0xba,
	0x5e, 0xaf, 0x39, 0xe8, 0xc6, 0x25, 0x2c, 0xfe, 0x0d, 0x8a, 0x2f, 0x9c, 0x8e, 0x96, 0x7a, 0xd2,
	0x81, 0x6d, 0xa9, 0x50, 0x33, 0x2b, 0x75, 0xf8, 0xdf, 0x61, 0xab, 0x37, 0x21, 0x50, 0x67, 0x5a,
	0x98, 0xb0, 0xee, 0xfa, 0xae, 0x8e, 0x0e, 0xc0, 0x5f, 0x13, 0x48, 0x00, 0x8d, 0xeb, 0xdb, 0x11,
	0x7d, 0x68, 0xd5, 0x08, 0x80, 0x7f, 0x76, 0x79, 0x77, 0x75, 0x3e, 0x6a, 0x79, 0x11, 0x85, 0x26,
	0x45, 0xb3, 0x98, 0x59, 0x8a, 0x46, 0xc9, 0xc2, 0xe0, 0x0a, 0x53, 0xb9, 0x6e, 0x50, 0x57, 0xaf,
	0x7a, 0x29, 0xb3, 0xcc, 0xd9, 0x0d, 0xa8, 0xab, 0x49, 0x08, 0x9b, 0x13, 0x94, 0x4e, 0x36, 0xcf,
	0xc1, 0xf8, 0xdb, 0x41, 0x6e, 0x50, 0x2f, 0x73, 0x8e, 0xe4, 0x04, 0xea, 0x06, 0x8b, 0x94, 0xec,
	0xfd, 0xf9, 0xd5, 0x4e, 0xbb, 0x1a, 0xfd, 0x74, 0x14, 0xd5, 0x86, 0x4f, 0xb0, 0x53, 0xce, 0x26,
	0x2f, 0x6c, 0xc9, 0x86, 0xbb, 0xd5, 0xf2, 0xfd, 0x3a, 0x94, 0xf1, 0x2a, 0x93, 0xb1, 0xf7, 0x78,
	0x24, 0x72, 0x9b, 0x2d, 0xa6, 0x31, 0x97, 0xf3, 0x24, 0x7b, 0x57, 0xa8, 0x67, 0x98, 0x0a, 0xd4,
	0xc9, 0x33, 0x9b, 0xea, 0x9c, 0xf7, 0xf9, 0x2c, 0xc7, 0xc2, 0xf6, 0x85, 0x4c, 0x84, 0x56, 0x3c,
	0x29, 0x99, 0x53, 0xdf, 0x45, 0x7a, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x26, 0x95, 0xa4,
	0xed, 0x01, 0x00, 0x00,
}
